/**
 * @file weights.h
 * @brief Master header for all TinySentiment weights
 * @note Auto-generated by export_sentiment_weights.py
 */

#ifndef WEIGHTS_H
#define WEIGHTS_H

// Model configuration
#define MODEL_VOCAB_SIZE   30522
#define MODEL_MAX_POSITION 64
#define MODEL_D_MODEL      128
#define MODEL_N_HEADS      2
#define MODEL_D_K          64
#define MODEL_D_FF         256
#define MODEL_N_LAYERS     2
#define MODEL_NUM_LABELS   2

// Include all weight files
#include "embedding_token.h"
#include "embedding_position.h"
#include "layer0.h"
#include "layer1.h"
#include "classifier.h"

#endif // WEIGHTS_H
