/**
 * @file weights.h
 * @brief Master header for pre-trained sentiment model weights
 * @note Auto-generated by export_sentiment_pretrained.py
 *
 * This model uses pre-trained BERT-tiny weights fine-tuned on SST-2.
 */

#ifndef WEIGHTS_H
#define WEIGHTS_H

// Model configuration (bert-tiny architecture)
#define MODEL_VOCAB_SIZE   30522
#define MODEL_MAX_POSITION 512
#define MODEL_D_MODEL      128
#define MODEL_N_HEADS      2
#define MODEL_D_K          64
#define MODEL_D_FF         512
#define MODEL_N_LAYERS     2
#define MODEL_NUM_LABELS   2

// Pre-trained model info
#define MODEL_PRETRAINED   1
#define MODEL_BASE         "bert-tiny"

// Include all weight files
#include "embedding_token.h"
#include "embedding_position.h"
#include "embedding_token_type.h"
#include "embedding_layernorm.h"
#include "layer0.h"
#include "layer1.h"
#include "classifier.h"

#endif // WEIGHTS_H
